org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=D:/DevCache/tmp
android.useAndroidX=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.workers.max=2
org.gradle.caching=true
android.lint.checkReleaseBuilds=false
