class CountryOption {
  const CountryOption(this.code, this.name);

  final String code;
  final String name;
}

const shippingCountries = <CountryOption>[
  CountryOption('AF', 'Afghanistan'),
  CountryOption('AL', 'Albania'),
  CountryOption('DZ', 'Algeria'),
  CountryOption('AD', 'Andorra'),
  CountryOption('AO', 'Angola'),
  CountryOption('AG', 'Antigua and Barbuda'),
  CountryOption('AR', 'Argentina'),
  CountryOption('AM', 'Armenia'),
  CountryOption('AU', 'Australia'),
  CountryOption('AT', 'Austria'),
  CountryOption('AZ', 'Azerbaijan'),
  CountryOption('BS', 'Bahamas'),
  CountryOption('BH', 'Bahrain'),
  CountryOption('BD', 'Bangladesh'),
  CountryOption('BB', 'Barbados'),
  CountryOption('BY', 'Belarus'),
  CountryOption('BE', 'Belgium'),
  CountryOption('BZ', 'Belize'),
  CountryOption('BJ', 'Benin'),
  CountryOption('BT', 'Bhutan'),
  CountryOption('BO', 'Bolivia'),
  CountryOption('BA', 'Bosnia and Herzegovina'),
  CountryOption('BW', 'Botswana'),
  CountryOption('BR', 'Brazil'),
  CountryOption('BN', 'Brunei'),
  CountryOption('BG', 'Bulgaria'),
  CountryOption('BF', 'Burkina Faso'),
  CountryOption('BI', 'Burundi'),
  CountryOption('CV', 'Cabo Verde'),
  CountryOption('KH', 'Cambodia'),
  CountryOption('CM', 'Cameroon'),
  CountryOption('CA', 'Canada'),
  CountryOption('CF', 'Central African Republic'),
  CountryOption('TD', 'Chad'),
  CountryOption('CL', 'Chile'),
  CountryOption('CN', 'China'),
  CountryOption('CO', 'Colombia'),
  CountryOption('KM', 'Comoros'),
  CountryOption('CG', 'Congo'),
  CountryOption('CD', 'Congo, Democratic Republic'),
  CountryOption('CR', 'Costa Rica'),
  CountryOption('CI', "Cote d'Ivoire"),
  CountryOption('HR', 'Croatia'),
  CountryOption('CU', 'Cuba'),
  CountryOption('CY', 'Cyprus'),
  CountryOption('CZ', 'Czechia'),
  CountryOption('DK', 'Denmark'),
  CountryOption('DJ', 'Djibouti'),
  CountryOption('DM', 'Dominica'),
  CountryOption('DO', 'Dominican Republic'),
  CountryOption('EC', 'Ecuador'),
  CountryOption('EG', 'Egypt'),
  CountryOption('SV', 'El Salvador'),
  CountryOption('GQ', 'Equatorial Guinea'),
  CountryOption('ER', 'Eritrea'),
  CountryOption('EE', 'Estonia'),
  CountryOption('SZ', 'Eswatini'),
  CountryOption('ET', 'Ethiopia'),
  CountryOption('FJ', 'Fiji'),
  CountryOption('FI', 'Finland'),
  CountryOption('FR', 'France'),
  CountryOption('GA', 'Gabon'),
  CountryOption('GM', 'Gambia'),
  CountryOption('GE', 'Georgia'),
  CountryOption('DE', 'Germany'),
  CountryOption('GH', 'Ghana'),
  CountryOption('GR', 'Greece'),
  CountryOption('GD', 'Grenada'),
  CountryOption('GT', 'Guatemala'),
  CountryOption('GN', 'Guinea'),
  CountryOption('GW', 'Guinea-Bissau'),
  CountryOption('GY', 'Guyana'),
  CountryOption('HT', 'Haiti'),
  CountryOption('HN', 'Honduras'),
  CountryOption('HU', 'Hungary'),
  CountryOption('IS', 'Iceland'),
  CountryOption('IN', 'India'),
  CountryOption('ID', 'Indonesia'),
  CountryOption('IR', 'Iran'),
  CountryOption('IQ', 'Iraq'),
  CountryOption('IE', 'Ireland'),
  CountryOption('IL', 'Israel'),
  CountryOption('IT', 'Italy'),
  CountryOption('JM', 'Jamaica'),
  CountryOption('JP', 'Japan'),
  CountryOption('JO', 'Jordan'),
  CountryOption('KZ', 'Kazakhstan'),
  CountryOption('KE', 'Kenya'),
  CountryOption('KI', 'Kiribati'),
  CountryOption('KP', 'Korea, North'),
  CountryOption('KR', 'Korea, South'),
  CountryOption('XK', 'Kosovo'),
  CountryOption('KW', 'Kuwait'),
  CountryOption('KG', 'Kyrgyzstan'),
  CountryOption('LA', 'Laos'),
  CountryOption('LV', 'Latvia'),
  CountryOption('LB', 'Lebanon'),
  CountryOption('LS', 'Lesotho'),
  CountryOption('LR', 'Liberia'),
  CountryOption('LY', 'Libya'),
  CountryOption('LI', 'Liechtenstein'),
  CountryOption('LT', 'Lithuania'),
  CountryOption('LU', 'Luxembourg'),
  CountryOption('MG', 'Madagascar'),
  CountryOption('MW', 'Malawi'),
  CountryOption('MY', 'Malaysia'),
  CountryOption('MV', 'Maldives'),
  CountryOption('ML', 'Mali'),
  CountryOption('MT', 'Malta'),
  CountryOption('MH', 'Marshall Islands'),
  CountryOption('MR', 'Mauritania'),
  CountryOption('MU', 'Mauritius'),
  CountryOption('MX', 'Mexico'),
  CountryOption('FM', 'Micronesia'),
  CountryOption('MD', 'Moldova'),
  CountryOption('MC', 'Monaco'),
  CountryOption('MN', 'Mongolia'),
  CountryOption('ME', 'Montenegro'),
  CountryOption('MA', 'Morocco'),
  CountryOption('MZ', 'Mozambique'),
  CountryOption('MM', 'Myanmar'),
  CountryOption('NA', 'Namibia'),
  CountryOption('NR', 'Nauru'),
  CountryOption('NP', 'Nepal'),
  CountryOption('NL', 'Netherlands'),
  CountryOption('NZ', 'New Zealand'),
  CountryOption('NI', 'Nicaragua'),
  CountryOption('NE', 'Niger'),
  CountryOption('NG', 'Nigeria'),
  CountryOption('MK', 'North Macedonia'),
  CountryOption('NO', 'Norway'),
  CountryOption('OM', 'Oman'),
  CountryOption('PK', 'Pakistan'),
  CountryOption('PW', 'Palau'),
  CountryOption('PS', 'Palestine'),
  CountryOption('PA', 'Panama'),
  CountryOption('PG', 'Papua New Guinea'),
  CountryOption('PY', 'Paraguay'),
  CountryOption('PE', 'Peru'),
  CountryOption('PH', 'Philippines'),
  CountryOption('PL', 'Poland'),
  CountryOption('PT', 'Portugal'),
  CountryOption('QA', 'Qatar'),
  CountryOption('RO', 'Romania'),
  CountryOption('RU', 'Russia'),
  CountryOption('RW', 'Rwanda'),
  CountryOption('KN', 'Saint Kitts and Nevis'),
  CountryOption('LC', 'Saint Lucia'),
  CountryOption('VC', 'Saint Vincent and the Grenadines'),
  CountryOption('WS', 'Samoa'),
  CountryOption('SM', 'San Marino'),
  CountryOption('ST', 'Sao Tome and Principe'),
  CountryOption('SA', 'Saudi Arabia'),
  CountryOption('SN', 'Senegal'),
  CountryOption('RS', 'Serbia'),
  CountryOption('SC', 'Seychelles'),
  CountryOption('SL', 'Sierra Leone'),
  CountryOption('SG', 'Singapore'),
  CountryOption('SK', 'Slovakia'),
  CountryOption('SI', 'Slovenia'),
  CountryOption('SB', 'Solomon Islands'),
  CountryOption('SO', 'Somalia'),
  CountryOption('ZA', 'South Africa'),
  CountryOption('SS', 'South Sudan'),
  CountryOption('ES', 'Spain'),
  CountryOption('LK', 'Sri Lanka'),
  CountryOption('SD', 'Sudan'),
  CountryOption('SR', 'Suriname'),
  CountryOption('SE', 'Sweden'),
  CountryOption('CH', 'Switzerland'),
  CountryOption('SY', 'Syria'),
  CountryOption('TW', 'Taiwan'),
  CountryOption('TJ', 'Tajikistan'),
  CountryOption('TZ', 'Tanzania'),
  CountryOption('TH', 'Thailand'),
  CountryOption('TL', 'Timor-Leste'),
  CountryOption('TG', 'Togo'),
  CountryOption('TO', 'Tonga'),
  CountryOption('TT', 'Trinidad and Tobago'),
  CountryOption('TN', 'Tunisia'),
  CountryOption('TR', 'Turkiye'),
  CountryOption('TM', 'Turkmenistan'),
  CountryOption('TV', 'Tuvalu'),
  CountryOption('UG', 'Uganda'),
  CountryOption('UA', 'Ukraine'),
  CountryOption('AE', 'United Arab Emirates'),
  CountryOption('GB', 'United Kingdom'),
  CountryOption('US', 'United States'),
  CountryOption('UY', 'Uruguay'),
  CountryOption('UZ', 'Uzbekistan'),
  CountryOption('VU', 'Vanuatu'),
  CountryOption('VA', 'Vatican City'),
  CountryOption('VE', 'Venezuela'),
  CountryOption('VN', 'Vietnam'),
  CountryOption('YE', 'Yemen'),
  CountryOption('ZM', 'Zambia'),
  CountryOption('ZW', 'Zimbabwe'),
];

CountryOption shippingCountry(String code) {
  return shippingCountries.firstWhere(
    (country) => country.code == code.toUpperCase(),
    orElse: () =>
        shippingCountries.firstWhere((country) => country.code == 'US'),
  );
}
